#!/bin/sh
# Add permissions for all users to run a chef-client

LINE='ALL ALL=NOPASSWD: /usr/bin/gecos-chef-client-wrapper'
FILE=/etc/sudoers

grep -q "$LINE" "$FILE" || echo "$LINE" >> "$FILE" 

# Set the services to start at boot
systemctl enable gecos-snitch-service.service
systemctl enable gecos-first-login.service

# Disable chef client service
systemctl disable chef-client.service
