#!/usr/bin/python
# -*- Mode: Python; coding: utf-8; indent-tabs-mode: nil; tab-width: 4 -*-

# This file is part of Guadalinex
#
# This software is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this package; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

__author__ = "Antonio Hernández <ahernandez@emergya.com>"
__copyright__ = "Copyright (C) 2011, Junta de Andalucía <gecos@guadalinex.org>"
__license__ = "GPL-2"


import sys
import os

import gettext
from gettext import gettext as _

from gecosfirstlogin import dbusservice
from gecosfirstlogin_lib.config import get_prefix

PYTHON_VERSION = ".".join(map(str, sys.version_info[:2]))
# Just in case folders have the third version number
PYTHON_VERSION_FULL = ".".join(map(str, sys.version_info[:3]))

# Add project root directory (enable symlink and trunk execution)
PROJECT_ROOT_DIRECTORY = os.path.abspath(
    os.path.dirname(os.path.dirname(os.path.realpath(sys.argv[0]))))

python_path = []
if os.path.abspath(__file__).startswith('/opt'):
    syspath = sys.path[:] # copy to avoid infinite loop in pending objects
    for path in syspath:
        opt_path = path.replace('/usr', '/opt/extras.ubuntu.com/firstart')
        python_path.insert(0, opt_path)
        sys.path.insert(0, opt_path)

if (os.path.exists(os.path.join(PROJECT_ROOT_DIRECTORY, 'firstart'))
        and PROJECT_ROOT_DIRECTORY not in sys.path):
    python_path.insert(0, PROJECT_ROOT_DIRECTORY)
    sys.path.insert(0, PROJECT_ROOT_DIRECTORY)


def insert_paths(paths=[]):
    for path in paths:
        if os.path.exists(path) and path not in sys.path:
            python_path.insert(0, path)
            sys.path.insert(0, path)



insert_paths([
    '/usr/local/lib/python' + PYTHON_VERSION + '/dist-packages',
    '/usr/lib/python' + PYTHON_VERSION + '/dist-packages',
    '/usr/local/lib/python' + PYTHON_VERSION + '/site-packages',
    '/usr/lib/python' + PYTHON_VERSION + '/site-packages',
    '/usr/local/lib/python' + PYTHON_VERSION_FULL + '/dist-packages',
    '/usr/lib/python' + PYTHON_VERSION_FULL + '/dist-packages',
    '/usr/local/lib/python' + PYTHON_VERSION_FULL + '/site-packages',
    '/usr/lib/python' + PYTHON_VERSION_FULL + '/site-packages',
    #'/usr/local/share/pyshared',
    #'/usr/share/pyshared'
])


if python_path:
    os.putenv('PYTHONPATH', "%s:%s" % (os.getenv('PYTHONPATH', ''), ':'.join(python_path))) # for subprocesses



if get_prefix() == '/usr/local':
    gettext.bindtextdomain('firstart', '/usr/local/share/locale')
elif get_prefix() == '/usr':
    gettext.textdomain('firstart')


if __name__ == '__main__':

    dbusservice()
